
name: "Lesson 2 - Exercise 3"

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Prevent reruns
        run: |
          # Exit if the run number is greater than the maximum number of attempts
          if [ $RUN_ATTEMPT_NUMBER -gt $MAXIMUM_ATTEMPTS ]; then
            echo "Exiting because the run number is greater than the maximum number of attempts."
            exit 1
          fi
          # Add solution below this line
          # Learn more about context: https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
          # Lern more about environment variables: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idenv
      - name: Run job
        run: |
          echo "Running job"
          sleep 1
          
